check50:
  files: &check50_files
    - !exclude "*"
    - !include colorize.c
    - !include smiley.bmp
    - !include output.bmp
    - !include helpers.h
    - !include helpers.c
    - !include Makefile

submit50:
  files: *check50_files
