check50:
  files: &check50_files
    - !exclude "*"
    - !include colorize.c
    - !include smiley.bmp
    - !include output.bmp
    - !include header.h
    - !include header.c

submit50:
  files: *check50_files
